source 'http://dev.byai.uk:9090/repository/cocoapods/'

# inhibit_all_warnings!
use_frameworks!

abstract_target 'core' do

  pod 'SSZipArchive', :path => '..'
  pod 'Alamofire', '~>5.0.0-beta.5'
  pod 'Igor'
  pod 'SafetySDK'
  pod 'DSTestDR'


  target 'ObjectiveCExample' do
    platform :ios, '15.5'
  end

  target 'ObjectiveCExampleTests_iOS' do
    platform :ios, '15.5'
  end

  target 'ObjectiveCExampleTests_macOS' do
    platform :osx, '10.15'
  end

  target 'ObjectiveCExampleTests_tvOS' do
    platform :tvos, '15.4'
  end

  target 'SwiftExample' do
    platform :ios, '15.5'
  end
  
  target 'SwiftExample_macOS' do
    platform :osx, '10.15'
  end
  
end
